version: '3'

services:
  desafiobix-airflow:
    image: desafiobix:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: airflow standalone
    